version: '3.9'

services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.14
    user: "1883:996"
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
    volumes:
      - ./mosquitto/:/mosquitto/:rw
    env_file:
      - .env

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.22.2
    network_mode: host
    restart: always
    volumes:
      - ./zigbee2mqtt:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - mosquitto
