version: '3.9'

services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.14
    user: 1883:996
    ports:
      - 1883:1883
      - 9001:9001
    restart: unless-stopped
    volumes:
      - ./mosquitto/:/mosquitto/:rw
    env_file:
      - .env

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.22.2
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt:/app/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    depends_on:
      - mosquitto

  node-red:
    container_name: node-red
    image: nodered/node-red:2.1.6
    ports:
      - 1880:1880
    restart: unless-stopped
    volumes:
      - ./node-red:/data
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    env_file:
      - .env
    depends_on:
      - mosquitto
    environment:
      - TZ=Europe/Prague

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:2022.2
    volumes:
      # Local path where your home assistant config will be stored
      - ./home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mosquitto
