version: '3.9'

services:

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:2.0.18
    user: 1883:996
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
    volumes:
      - ./mosquitto/:/mosquitto/:rw
    env_file:
      - .env

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt:1.33.2
    network_mode: host
    restart: always
    volumes:
      - ./zigbee2mqtt:/app/data
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    depends_on:
      - mosquitto

  node-red:
    container_name: node-red
    image: nodered/node-red:3.1.0
    ports:
      - 1880:1880
    restart: always
    volumes:
      - ./node-red:/data
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    env_file:
      - .env
    depends_on:
      - mosquitto
    environment:
      - TZ=Europe/Prague

  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:2023.10
    volumes:
      - ./home-assistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mosquitto
      - mariadb
  
  code-server:
    container_name: code-server
    image: linuxserver/code-server:4.18.0
    restart: unless-stopped
    ports:
      - 8443:8443
    volumes:
      - ./vscode:/config
      - ./home-assistant:/config/workspace
    environment:
      - TZ=Europe/Prague
      - PUID=1000
      - PGID=1000

  mariadb:
    image: linuxserver/mariadb:10.11.5
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./mariadb:/var/lib/mysql
    ports:
      - "3306:3306"