# Home Assistant integration (MQTT discovery)
homeassistant: true

# allow new devices to join
permit_join: true

# MQTT settings
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
  user: '!secret user'
  password: '!secret password'

# Serial settings
serial:
  port: /dev/ttyUSB0
  baudrate: 115200
  disable_led: true
advanced:
  rtscts: false

# Devices settings
devices: devices.yaml